version: "3.9"

services:
  api:
    container_name: linkService
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1904:1904"
    env_file:
      - profile.env